#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Usage:
  ypconfig configtest [--cfg=configfile]
  ypconfig createconfig [--cfg=configfile]

Options:
  -h --help             Show this help
  --cfg=<configfile>    Location of the configfile [default: /etc/ypconfig/ypconfig.yml]
"""

import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), 'lib'))

from ypconfig import Config, Netlink
from docopt import docopt
from schema import Schema, And, Or, Use, SchemaError, Optional
from pprint import pprint

if __name__ == '__main__':
    args = docopt(__doc__)

    schema = Schema({
        '--cfg': str,
        'configtest': bool,
        'createconfig': bool
    })

    try:
        args = schema.validate(args)
    except SchemaError as e:
        sys.exit(e)

    if not args['createconfig']:
        try:
            cfgdoc = Config.Get(args['--cfg'])
        except FileNotFoundError as e:
            print(e)
            sys.exit(1)

    if args['configtest']:
        try:
            cfg = Config.Validate(cfgdoc)
        except Exception as e:
            print("Errors in configuration:\n - %s" % (e))
            sys.exit(1)
        else:
            print("Configuration is ok!")
    elif args['createconfig']:
        cfg = Netlink.GetNow()
        cfg = Config.Validate(cfg)
        Config.Set(args['--cfg'], cfg)
