name: Debian package

on:
  push:
    tags:
    - '*'

jobs:
  build_and_deploy:
    strategy:
      matrix:
        release: ["trixie", "bookworm", "bullseye"]

    # Debian packages should be built on Debian, on the release they're intended
    # for. But, GitHub Actions doesn't support hosted Debian runners. And it's
    # overkill to set up our own, because building on Ubuntu works well in practice.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update apt cache
        run: sudo apt-get update

      - name: Install required packages to build
        run: sudo apt-get -y install build-essential devscripts equivs dh-python

      - name: Install build dependencies
        run: sudo mk-build-deps -i -t 'apt -o Debug::pkgProblemResolver=yes --no-install-recommends -y'

      - name: Build package
        run: dpkg-buildpackage -us -uc

      - run: ls ./ ../

      # Workaround for https://github.com/actions/upload-artifact/issues/176
      - name: Get deb file path
        run: echo "DEB_FILE_PATH=$(realpath ../*.deb)" >> $GITHUB_ENV

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: debian-package-${{ matrix.release }}
          path: ${{ env.DEB_FILE_PATH }}

      - name: Upload package to Packagecloud
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: ${{ env.DEB_FILE_PATH }}
          PACKAGECLOUD-USERNAME: ypconfig
          PACKAGECLOUD-REPO: ypconfig
          PACKAGECLOUD-DISTRIB: debian/${{ matrix.release }}
          PACKAGECLOUD-TOKEN: ${{ secrets.packagecloud_token }}
